imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User


easy_admin:
    site_name: 'Panel administratora'
    design:
            color_scheme: 'light'
    entities:
      User:
        label: 'klienci'
        class: AppBundle\Entity\User
        disabled_actions: ['new','edit']
        list:
          title: 'Konta klientów'
          fields:
                          - 'id'
                          - { property: 'userName', label: 'nazwa użytkownika' }
                          - { property: 'firstName', label: 'imię' }
                          - { property: 'lastName', label: 'nazwisko' }
                          - { property: 'email', label: 'adres email' }
          actions:
                          - { name: 'show', label: 'pokaż szczegóły' }
                          - { name: 'search', label: 'wyszukaj' }

      Order:
        label: 'zamówienia'
        class: AppBundle\Entity\Orders
        list:
          title: 'zamówienia'
          fields:
                          - 'id'
                          - { property: 'Products', label: 'zamówione produkty' }
                          - { property: 'isPaid', label: 'czy zapłacono', type: 'boolean' }
                          - { property: 'isSent', label: 'czy wysłano', type: 'boolean' }
                          - { property: 'Total cost', label: 'Całkowity koszt zamówienia' }
          actions:
                          - { name: 'new', label: 'nowe zamówienie' }
                          - { name: 'edit', label: 'modyfikuj' }
                          - { name: 'show', label: 'pokaż szczegóły' }
                          - { name: 'search', label: 'wyszukaj' }

      category:
        label: 'kategorie produktów'
        class: AppBundle\Entity\Category
        list:
             title: 'kategorie produktów'
             fields:
                           - 'id'
                           - { property: 'Name', label: 'nazwa kategorii' }
             actions:
                           - { name: 'new', label: 'nowa kategoria' }
                           - { name: 'edit', label: 'modyfikuj' }
                           - { name: 'show', label: 'pokaż szczegóły' }
                           - { name: 'search', label: 'wyszukaj' }

      Product:
        label: 'dostępne produkty'
        class: AppBundle\Entity\Product
        list:
            title: 'dostępne produkty'
            fields:
                           - 'id'
                           - { property: 'Name', label: 'nazwa produktu' }
                           - { property: 'Price', label: 'cena' }
                           - { property: 'Quantity', label: 'ilość dostępnych sztuk'}
                           - { property: 'Description', label: 'opis produktu' }
                           - { property: 'Category', label: 'kategoria produktu' }
            actions:
                            - { name: 'new', label: 'nowy produkt' }
                            - { name: 'edit', label: 'modyfikuj' }
                            - { name: 'show', label: 'pokaż szczegóły' }
                            - { name: 'search', label: 'wyszukaj' }

sylius_cart:
    resolver: app.cart_item_resolver # The id of our newly created service.
    classes: ~ # This key can be empty but it must be present in the configuration.

sylius_order:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    classes:
        order:
            model: AppBundle\Entity\Orders # If you have created a custom Cart entity.
        order_item:
            model: AppBundle\Entity\CartItem # If you have created a custom CartItem entity.

sylius_money: ~